'use strict';

const fs = require('fs');
const path = require('path');

exports.scaffold = function scaffold() {
  if (fs.existsSync('acg.yaml')) {
    console.log('acg.yaml already exists. Edit it directly.');
    return;
  }

  // Auto-detect runtime from project files
  const detectors = [
    ['package.json', 'node'],
    ['requirements.txt', 'python'],
    ['pyproject.toml', 'python'],
    ['Cargo.toml', 'rust'],
    ['go.mod', 'go'],
    ['index.html', 'static'],
  ];

  let runtime = 'python';
  for (const [file, lang] of detectors) {
    if (fs.existsSync(file)) {
      runtime = lang;
      break;
    }
  }

  const name = path.basename(process.cwd());

  const templates = {
    python: {
      entry: 'src/main.py',
      run: 'python src/main.py',
      test: 'pytest tests/ -v',
      build: 'python -m build',
      lint: 'ruff check .',
    },
    node: {
      entry: 'src/index.js',
      run: 'node src/index.js',
      test: 'npm test',
      build: 'npm run build',
      lint: 'eslint src/',
    },
    rust: {
      entry: 'src/main.rs',
      run: 'cargo run',
      test: 'cargo test',
      build: 'cargo build --release',
      lint: 'cargo clippy',
    },
    go: {
      entry: '.',
      run: 'go run .',
      test: 'go test ./...',
      build: 'go build .',
      lint: 'golangci-lint run',
    },
    static: {
      entry: 'index.html',
      run: 'python -m http.server 8080',
      test: 'echo "no tests configured"',
      build: 'echo "static site — no build needed"',
      lint: 'echo "ok"',
    },
  };

  const t = templates[runtime];

  const yaml = `# acg.yaml — ACG CLI configuration
# Generated by: acg init
# Docs: https://github.com/teslasolar/acgcli

name: ${name}
version: 0.1.0
description: "TODO: describe this project"
author: TODO
guild: acg

runtime:
  language: ${runtime}
  entry: ${t.entry}
  port: 8080

commands:
  run:
    cmd: "${t.run}"
    description: "Start the application"
  test:
    cmd: "${t.test}"
    description: "Run tests"
  build:
    cmd: "${t.build}"
    description: "Build"
  deploy:
    cmd: "echo 'Configure deploy in acg.yaml'"
    description: "Deploy"
    confirm: true
  lint:
    cmd: "${t.lint}"
    description: "Lint"
  clean:
    cmd: "rm -rf dist/ build/ __pycache__/ node_modules/.cache"
    description: "Clean artifacts"

health:
  - name: "Config valid"
    check: "node -e \\"require('js-yaml').load(require('fs').readFileSync('acg.yaml','utf8'))\\""

api:
  port: 9000
  cors: true

mcp:
  name: ${name}-mcp

ai:
  provider: local
  model: phi3
  context_files:
    - README.md
    - acg.yaml
`;

  fs.writeFileSync('acg.yaml', yaml);
  console.log(`\u2692 Created acg.yaml for ${name} (${runtime})`);
  console.log('  Edit the file, then run: acg status');
};
