// 📐 KONOMI:ACG-JS-015 | tokens:~230 | scope:runtime templates for acg init
'use strict';

const runtimeTemplates = {
  python: { entry: 'src/main.py', run: 'python src/main.py', test: 'pytest tests/ -v', build: 'python -m build', lint: 'ruff check .' },
  node: { entry: 'src/index.js', run: 'node src/index.js', test: 'npm test', build: 'npm run build', lint: 'eslint src/' },
  rust: { entry: 'src/main.rs', run: 'cargo run', test: 'cargo test', build: 'cargo build --release', lint: 'cargo clippy' },
  go: { entry: '.', run: 'go run .', test: 'go test ./...', build: 'go build .', lint: 'golangci-lint run' },
  static: { entry: 'index.html', run: 'python -m http.server 8080', test: 'echo "no tests configured"', build: 'echo "static site"', lint: 'echo "ok"' },
};

exports.runtimeTemplates = runtimeTemplates;

exports.generateYaml = function generateYaml(name, runtime) {
  const t = runtimeTemplates[runtime];
  return `# acg.yaml \u2014 ACG CLI configuration
# Generated by: acg init
name: ${name}
version: 0.1.0
description: "TODO: describe this project"
author: TODO
guild: acg

runtime:
  language: ${runtime}
  entry: ${t.entry}
  port: 8080

commands:
  run:
    cmd: "${t.run}"
    description: "Start the application"
  test:
    cmd: "${t.test}"
    description: "Run tests"
  build:
    cmd: "${t.build}"
    description: "Build"
  deploy:
    cmd: "echo 'Configure deploy in acg.yaml'"
    description: "Deploy"
    confirm: true
  lint:
    cmd: "${t.lint}"
    description: "Lint"
  clean:
    cmd: "rm -rf dist/ build/ __pycache__/ node_modules/.cache"
    description: "Clean artifacts"

health:
  - name: "Config valid"
    check: "node -e \\"require('js-yaml').load(require('fs').readFileSync('acg.yaml','utf8'))\\""

api:
  port: 9000
  cors: true

mcp:
  name: ${name}-mcp

ai:
  provider: local
  model: phi3
  context_files:
    - README.md
    - acg.yaml
`;
};
